services:
  txns:
    image: txns:latest
    restart: always
    ports:
      - 4000:4000
  adminer:
    image: docker.io/adminer:5.2.1
    restart: always
    ports:
      - 8080:8080
  db:
    image: docker.io/pgvector/pgvector:0.8.0-pg17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./data/.pg:/var/lib/postgresql/data"
