services:
  txns:
    image: txns:latest
    restart: always
    ports:
      - 3000:3000
  adminer:
    image: adminer:5.2.1
    restart: always
    ports:
      - 8080:8080
  db:
    image: pgvector/pgvector:0.8.0-pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./data/.pg:/var/lib/postgresql/data"
