CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID BIGSERIAL PRIMARY KEY,
    DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    AMOUNT_CENTS BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS TRANSACTIONS_INDEX 
ON TRANSACTIONS(DATE, DESCRIPTION, AMOUNT);