-- Enable pgvector extensions in the database.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID BIGSERIAL PRIMARY KEY,
    DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    AMOUNT_CENTS BIGINT NOT NULL,
    SOURCE VARCHAR(100) NOT NULL,
    TAGS VARCHAR(30)[],
    DESC_EMBEDDING VECTOR(768),
);

CREATE INDEX IF NOT EXISTS TRANSACTIONS_INDEX 
ON TRANSACTIONS(DATE, DESCRIPTION, AMOUNT_CENTS);